# -*- coding: utf-8 -*-
"""Advanced Pandas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wHFmE0jX2fhasqk4ZPPHgc5lEF8Uv8ri
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_csv("Advanced_pandas_sales_dataset.csv")
df.head()

"""Q1 Dataset Exploration

Perform the following exploratory steps:

Display the first 10 rows

Display the dataset structure using info()

Find the number of rows and columns

Identify the data types of each column
"""

df.head(10)
df.info()
df.shape
df.dtypes

"""Q2 Sales Filtering Analysis

Filter the dataset to display:

Orders where Sales > 3500

Orders where Region = "East" and Sales > 2500

Explain what insights you observe
"""

high_sales = df[df['Sales'] > 3500]
high_sales

east_high_sales = df[(df['Region'] == 'East') & (df['Sales'] > 2500)]
east_high_sales

"""Q3 Customer Purchase Analysis

Identify the top 5 customers based on total sales.

Hint: Use GroupBy with aggregation.
"""

top_customers = df.groupby('Customer')['Sales'].sum()
top_customers

top_5_customers = top_customers.sort_values(ascending=False).head(5)
top_5_customers

"""Q4 Regional Sales Performance

Calculate the total sales generated by each region.

Then identify:

Which region generated the highest revenue?
"""

region_sales = df.groupby('Region')['Sales'].sum()
region_sales

region_sales_sorted = region_sales.sort_values(ascending=False)
region_sales_sorted

"""Q5 Product Performance Analysis

Calculate the total quantity sold for each product.

Which product appears to be the most popular?
"""

product_quantity = df.groupby('Product')['Quantity'].sum()
product_quantity
product_quantity_sorted = product_quantity.sort_values(ascending=False)
product_quantity_sorted

"""Q6 Multi-Level Grouping

Group the dataset by: Region and Category
Calculate the total sales for each combination.

What insights can you derive from this analysis?
"""

multi_group = df.groupby(['Region', 'Category'])['Sales'].sum()
multi_group
multi_group_unstacked = multi_group.unstack()
multi_group_unstacked

"""1. Category Performance by Region
Electronics dominates in most regions
High-value items → major revenue driver
2. East Region Strength
East likely shows highest sales across categories

Q7 Pivot Table Creation

Create a pivot table showing:

Rows → Region

Columns → Product

Values → Total Sales

Which region sells the most laptops?
"""

pivot_table = pd.pivot_table(
    df,
    values='Sales',
    index='Region',
    columns='Product',
    aggfunc='sum'
)

pivot_table

pivot_table['Laptop'].sort_values(ascending=False)

#East region sold the highest numbers of laptops

"""Q8 Profitability Analysis

Calculate the average profit for each product category.

Which category is most profitable?
"""

category_profit = df.groupby('Category')['Profit'].mean()
category_profit

category_profit.sort_values(ascending=False)

# Office category is most profitable.

"""Q9 Discount Impact Study

Analyze the relationship between discount and profit.

Tasks:

Calculate the average profit for each discount level

Identify whether higher discounts lead to lower profit
"""

discount_profit = df.groupby('Discount')['Profit'].mean()
discount_profit
discount_profit.sort_index()

"""Q10 End-to-End Data Wrangling Task

Perform the following workflow:

Filter the dataset where Sales > 3000

Group data by Region and Product

Calculate total sales

Reshape the result into a pivot table

Explain the business insights obtained from this analysis.
"""

filtered_df = df[df['Sales'] > 3000]
filtered_df

grouped = filtered_df.groupby(['Region', 'Product'])['Sales'].sum()
grouped

pivot_result = grouped.unstack()
pivot_result

"""Business Insights (This is what matters most)
1. High-Value Product Focus
Only products like:
Laptops, Phones, Printers
appear after filtering

Insight:

These are premium / revenue-driving products
2. Regional Strength in Premium Sales
East & South likely dominate high-value sales

Insight:

These regions have:
Higher purchasing power
Strong demand for expensive products
3. Product Concentration
Not all products appear in high sales

Insight:

Low-value items (like accessories) are excluded
Business is top-heavy (few products drive most revenue)
"""

