# -*- coding: utf-8 -*-
"""Data Cleaning Assignment

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1on_MXfamneKL07BgDddosHt92tsGxomn

Q1. Missing Data Identification

Scenario:
 The hospital suspects incomplete patient records.

Task:

Identify missing values in each column

Calculate percentage of missing data
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_csv("healthcare_data_cleaning_dataset.csv")
df.head()

df.isnull().sum()

(df.isnull().sum() / len(df)) * 100

"""Q2. Handling Missing Age

Scenario:
 Age is critical for medical analysis, but some values are missing.

Task:

Replace missing Age values with an appropriate method

Justify your choice (mean/median
"""

df['Age'].isnull().sum()
median_age = df['Age'].median()

df['Age'].fillna(median_age, inplace=True)

df['Age'].isnull().sum()

"""Q3. Handling Missing Treatment Cost

Scenario:
 Treatment cost is highly skewed due to expensive treatments.

Task:

Handle missing Treatment_Cost values

Choose the correct imputation method and explain why
"""

median_cost = df['Treatment_Cost'].median()
df['Treatment_Cost'] = df['Treatment_Cost'].fillna(median_cost)

df['Treatment_Cost'].isnull().sum()

"""Q4. Duplicate Patient Records

Scenario:
 Some patient records were entered multiple times.

Task:

Identify duplicate rows

Remove duplicates

Compare dataset size before and after
"""

# Step 1: Check dataset size before
print("Shape before removing duplicates:", df.shape)

# Step 2: Identify duplicate rows
duplicates = df.duplicated()
print("\nNumber of duplicate rows:", duplicates.sum())

# (Optional) View duplicate records
print("\nDuplicate rows preview:")
print(df[duplicates])

# Step 3: Remove duplicates
df = df.drop_duplicates()

# Step 4: Check dataset size after
print("\nShape after removing duplicates:", df.shape)

"""Q5. Invalid Age Values (Data Quality Check)

Scenario:
 Some patients have unrealistic age values (e.g., >100 or <0).

Task:

Detect such records

Decide whether to remove or correct them
"""

# Step 1: Detect invalid age values
invalid_age = df[(df['Age'] < 0) | (df['Age'] > 100)]

print("Invalid age records:")
print(invalid_age)

print("\nNumber of invalid records:", len(invalid_age))

# Step 2: Remove invalid records (recommended)
df_cleaned = df[(df['Age'] >= 0) & (df['Age'] <= 100)]

print("\nShape before cleaning:", df.shape)
print("Shape after cleaning:", df_cleaned.shape)

"""Q6. Outlier Detection (Treatment Cost)

Scenario:
 Extreme treatment costs are affecting analysis.

Task:

Detect outliers using IQR method

Display number of outliers
"""

# Step 1: Calculate Q1 and Q3
Q1 = df['Treatment_Cost'].quantile(0.25)
Q3 = df['Treatment_Cost'].quantile(0.75)

# Step 2: Calculate IQR
IQR = Q3 - Q1

# Step 3: Define bounds
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# Step 4: Detect outliers
outliers = df[(df['Treatment_Cost'] < lower_bound) |
              (df['Treatment_Cost'] > upper_bound)]

# Step 5: Display results
print("Lower Bound:", lower_bound)
print("Upper Bound:", upper_bound)

print("\nNumber of outliers:", len(outliers))

print("\nOutlier records preview:")
print(outliers.head())

"""Q7. Outlier Treatment

Scenario:
The business team wants to retain all records.

Task:

Apply capping (Winsorization) on Treatment_Cost

Use 5th and 95th percentile
"""

# Step 1: Calculate percentiles
lower_cap = df['Treatment_Cost'].quantile(0.05)
upper_cap = df['Treatment_Cost'].quantile(0.95)

print("Lower Cap (5th percentile):", lower_cap)
print("Upper Cap (95th percentile):", upper_cap)

# Step 2: Apply capping (Winsorization)
df['Treatment_Cost'] = df['Treatment_Cost'].clip(lower=lower_cap, upper=upper_cap)

# Step 3: Verify
print("\nAfter capping:")
print(df['Treatment_Cost'].describe())

"""Q8. Transformation

Scenario:
 Treatment cost is highly skewed.

Task:

Apply log transformation

Create a new column

Compare before vs after distribution
"""

import numpy as np
import matplotlib.pyplot as plt

# Step 1: Apply log transformation (use log1p to handle zero values safely)
df['Log_Treatment_Cost'] = np.log1p(df['Treatment_Cost'])

# Step 2: Compare distributions (Before vs After)

plt.figure(figsize=(12,5))

# Before
plt.subplot(1,2,1)
plt.hist(df['Treatment_Cost'], bins=30)
plt.title("Before Transformation")

# After
plt.subplot(1,2,2)
plt.hist(df['Log_Treatment_Cost'], bins=30)
plt.title("After Log Transformation")

plt.show()

# Step 3: Quick stats comparison
print("Before Transformation:")
print(df['Treatment_Cost'].describe())

print("\nAfter Transformation:")
print(df['Log_Treatment_Cost'].describe())

"""Q9. Time-Based Missing Handling

Scenario:
 Admission dates should follow a logical sequence.

Task:

Sort data by Admission_Date

Apply forward fill or backward fill where appropriate

Justify your choice
"""

# Step 1: Convert to datetime (if not already done)
df['Admission_Date'] = pd.to_datetime(df['Admission_Date'])

# Step 2: Sort data by Admission_Date
df = df.sort_values(by='Admission_Date')

# Step 3: Apply forward fill (ffill)
df = df.ffill()

# (Optional) If needed, apply backward fill for starting nulls
df = df.bfill()

# Step 4: Verify
print(df.isnull().sum())
df.head()