# -*- coding: utf-8 -*-
"""Data Transformation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d0vt5dDhUJBMEmMimPEcPSueAA9LCYgH
"""

# Import libraries
from google.colab import files
import pandas as pd

# Upload file
uploaded = files.upload()

# Read uploaded CSV file automatically
df = pd.read_csv(next(iter(uploaded)))

# Display first 5 rows
df.head()

"""Assignment Questions

Q1. Handle Missing Values (Basic Cleaning)

Fill missing values using the following:

Age → Median

Salary → Mean

Hours_Worked_Per_Week → Median

Performance_Score → Mean

Display the dataset after handling missing values.
"""

# Check missing values before cleaning
print("Missing Values Before Cleaning:\n")
print(df.isnull().sum())

# Fill missing values

# Age -> Median
df['Age'] = df['Age'].fillna(df['Age'].median())

# Salary -> Mean
df['Salary'] = df['Salary'].fillna(df['Salary'].mean())

# Hours_Worked_Per_Week -> Median
df['Hours_Worked_Per_Week'] = df['Hours_Worked_Per_Week'].fillna(
    df['Hours_Worked_Per_Week'].median()
)

# Performance_Score -> Mean
df['Performance_Score'] = df['Performance_Score'].fillna(
    df['Performance_Score'].mean()
)

# Check missing values after cleaning
print("\nMissing Values After Cleaning:\n")
print(df.isnull().sum())

# Display cleaned dataset
print("\nDataset After Handling Missing Values:\n")
print(df.head())

"""Q2. Label Encoding

Convert these columns into numeric values using Label Encoding:

Gender

Department

Show the updated columns.
"""

from sklearn.preprocessing import LabelEncoder

# Create LabelEncoder object
le = LabelEncoder()

# Apply Label Encoding

# Gender
df['Gender_Encoded'] = le.fit_transform(df['Gender'])

# Department
df['Department_Encoded'] = le.fit_transform(df['Department'])

# Display updated columns
print(df[['Gender', 'Gender_Encoded',
          'Department', 'Department_Encoded']].head(10))

"""Q3. One-Hot Encoding

Apply One-Hot Encoding on:

Work_Mode

Location

Display the dataset and check how many new columns are created.
"""

# Apply One-Hot Encoding
df_encoded = pd.get_dummies(df, columns=['Work_Mode', 'Location'])

# Display dataset
print("Updated Dataset:\n")
print(df_encoded.head())

# Check total columns after encoding
print("\nTotal Columns After Encoding:", df_encoded.shape[1])

# Show newly created columns
new_columns = [col for col in df_encoded.columns
               if 'Work_Mode_' in col or 'Location_' in col]

print("\nNewly Created Columns:\n")
print(new_columns)

"""Q4. Normalization (Min-Max Scaling)

Normalize the following columns:

Salary

Hours_Worked_Per_Week

Use MinMaxScaler and display results
"""

from sklearn.preprocessing import MinMaxScaler

# Create scaler object
scaler = MinMaxScaler()

# Normalize selected columns
df[['Salary_Normalized', 'Hours_Normalized']] = scaler.fit_transform(
    df[['Salary', 'Hours_Worked_Per_Week']]
)

# Display results
print(df[['Salary',
          'Salary_Normalized',
          'Hours_Worked_Per_Week',
          'Hours_Normalized']].head())

"""Q5. Standardization (Scaling)

Apply StandardScaler on:

*Age.
*Projects_Completed

Display the transformed values.
"""

from sklearn.preprocessing import StandardScaler

# Create scaler object
scaler = StandardScaler()

# Apply Standardization
df[['Age_Standardized', 'Projects_Standardized']] = scaler.fit_transform(
    df[['Age', 'Projects_Completed']]
)

# Display transformed values
print(df[['Age',
          'Age_Standardized',
          'Projects_Completed',
          'Projects_Standardized']].head())

"""Q6. Compare Scaling Methods

Apply both:

MinMaxScaler

StandardScaler

On the Salary column.

Show both results side by side.
"""

from sklearn.preprocessing import MinMaxScaler, StandardScaler

# Create scaler objects
minmax_scaler = MinMaxScaler()
standard_scaler = StandardScaler()

# Apply Min-Max Scaling
df['Salary_MinMax'] = minmax_scaler.fit_transform(df[['Salary']])

# Apply Standard Scaling
df['Salary_Standardized'] = standard_scaler.fit_transform(df[['Salary']])

# Display results side by side
print(df[['Salary',
          'Salary_MinMax',
          'Salary_Standardized']].head(10))

"""Q7. Build Preprocessing Pipeline

Create a pipeline that:

Applies encoding to categorical columns

Applies scaling to numerical columns

Use:

ColumnTransformer

Pipeline
"""

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
import pandas as pd

# Define categorical and numerical columns
categorical_cols = ['Gender', 'Department', 'Work_Mode', 'Location']

numerical_cols = [
    'Age',
    'Salary',
    'Hours_Worked_Per_Week',
    'Projects_Completed',
    'Performance_Score'
]

# Create preprocessing steps

# Categorical Transformer -> OneHotEncoding
categorical_transformer = OneHotEncoder(handle_unknown='ignore')

# Numerical Transformer -> Standard Scaling
numerical_transformer = StandardScaler()

# Combine using ColumnTransformer
preprocessor = ColumnTransformer(
    transformers=[
        ('cat', categorical_transformer, categorical_cols),
        ('num', numerical_transformer, numerical_cols)
    ]
)

# Create Pipeline
pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor)
])

# Apply pipeline
processed_data = pipeline.fit_transform(df)

# Convert processed data into DataFrame
processed_df = pd.DataFrame(
    processed_data,
    columns=preprocessor.get_feature_names_out()
)

# Display output
print(processed_df.head())

"""Q8. Apply Pipeline

Apply the pipeline on the dataset.

Display:

Transformed dataset

Shape of final dataset
"""

# Apply pipeline on dataset
processed_data = pipeline.fit_transform(df)

# Convert transformed data into DataFrame
processed_df = pd.DataFrame(
    processed_data,
    columns=preprocessor.get_feature_names_out()
)

# Display transformed dataset
print("Transformed Dataset:\n")
print(processed_df.head())

# Display shape of final dataset
print("\nShape of Final Dataset:")
print(processed_df.shape)

"""Q9. Conceptual Question

Why is scaling important in Python?

easons Why Scaling is Important
1. Prevents Large Values from Dominating

Features like Salary may have very large values compared to Age or Hours Worked.

Without scaling:

Algorithms may give more importance to larger-number features.

Example:

Salary = 90000
Age = 25

 Salary dominates because of its magnitude.

2. Improves Model Performance

Scaling helps machine learning models learn patterns more efficiently and accurately.

Especially important for:

KNN
SVM
Logistic Regression
Neural Networks
PCA
3. Faster Convergence

Gradient-based algorithms converge faster when data is scaled.

 Training becomes:

Faster
More stable
4. Improves Distance Calculations

Algorithms using distance formulas are highly affected by feature scale.

Q10. Conceptual Question

Why do we convert categorical data into numerical form?

Machine learning algorithms work with mathematical calculations and cannot directly understand text or categorical values.

Therefore, categorical data must be converted into numerical form before applying machine learning models.

 Reasons for Converting Categorical Data
1. Machine Learning Models Understand Numbers

Algorithms perform operations like:

Distance calculation
Matrix computation
Gradient optimization

Text values like:

Male, Female, HR, IT

cannot be processed directly.

2. Enables Mathematical Computation

Models require numerical input for formulas and calculations.

Example:

y=mx+b
m
b
-10
-8
-6
-4
-2
2
4
6
8
10
-10
-5
5
10
y-intercept
x-intercept

Algorithms can only compute numerical values.

3. Improves Model Training

Numerical encoding allows models to:

Learn patterns
Compare categories
Make predictions efficiently
"""