# -*- coding: utf-8 -*-
"""Decision Tree

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13abmB5hVaP29nOp3rHLcylVEqCMHonO5

Q1. What is a Decision Tree? Explain its structure (Root, Nodes, Leaves) with a real-life example.

What is a Decision Tree?

A Decision Tree is a supervised machine learning algorithm used for:

Classification (Yes/No, Approved/Rejected, Spam/Not Spam)
Regression (Predicting numerical values)

It works by repeatedly splitting data into smaller groups based on certain conditions, similar to how humans make decisions.

Think of it as a flowchart where each question leads to another question until a final decision is reached.

Structure of a Decision Tree

A Decision Tree consists of three main parts:

1. Root Node

The Root Node is the topmost node of the tree.

Represents the entire dataset.
The first decision or question is made here.
It is the starting point of the tree.

Example:

Is Credit Score > 700?

This is the first question asked for every loan applicant.

2. Decision Nodes (Internal Nodes)

Decision Nodes are intermediate nodes where further splitting occurs.

Each node asks another question based on a feature.

Example:

Is Credit Score > 700?
       /      \
     Yes      No

If the answer is "Yes," the tree may ask:

Is Income > ₹50,000?
3. Leaf Nodes (Terminal Nodes)

Leaf Nodes represent the final outcome or prediction.

No further splitting occurs.

Example:

Loan Approved

or

Loan Rejected
Real-Life Example: Loan Approval

Suppose a bank wants to decide whether to approve a loan.

                    Credit Score > 700?
                          /      \
                        Yes       No
                        /          \
           Income > ₹50,000?      Reject
                /      \
              Yes      No
              /          \
          Approve      Reject
How It Works
Applicant 1
Credit Score = 750
Income = ₹60,000

Path:

Credit Score > 700? → Yes
Income > ₹50,000? → Yes

Result:

Loan Approved
Applicant 2
Credit Score = 650

Path:

Credit Score > 700? → No

Result:

Loan Rejected
Visual Representation
                    ROOT NODE
             Credit Score > 700?
                  /          \
               Yes            No
               /               \
     Income > ₹50,000?       LEAF
          /      \           Reject
        Yes      No
        /         \
      LEAF       LEAF
    Approve     Reject

Q2. Differentiate between Gini Impurity and Entropy.
Which one is used by default in Scikit-learn and why?

Both Gini Impurity and Entropy are metrics used in Decision Trees to determine the best feature for splitting the data.

The goal of both measures is to create nodes that are as pure as possible.

1. Gini Impurity

Gini measures the probability of incorrectly classifying a randomly chosen sample.

Formula

Gini=1−∑p
i
2
	​


Where:

p
i
	​

 = probability of class i
Example

Suppose a node contains:

80% Approved Loans
20% Rejected Loans

Then:

Gini = 1 - (0.8² + 0.2²)
      = 1 - (0.64 + 0.04)
      = 0.32
Interpretation
Gini = 0 → Pure node
Higher Gini → More impurity
2. Entropy

Entropy measures the amount of uncertainty or randomness in the data.

It comes from Information Theory.

Formula

Entropy=−∑p
i
	​

log
2
	​

(p
i
	​

)

Example

For:

80% Approved
20% Rejected
Entropy = -(0.8 log₂0.8 + 0.2 log₂0.2)
         ≈ 0.72
Interpretation
Entropy = 0 → Perfectly pure node
Higher entropy → More uncertainty


By default, Scikit-Learn uses:

criterion='gini'

Example:

from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier()

This automatically means:

DecisionTreeClassifier(criterion='gini')

Q3. What is Overfitting in Decision Trees?
How can we detect it using training and testing accuracy?

What is Overfitting?

Overfitting occurs when a Decision Tree learns the training data too well, including noise and random patterns, instead of learning the underlying relationships.

As a result:

Performs extremely well on training data.
Performs poorly on unseen test data.
Cannot generalize to new observations.
Real-Life Example

Suppose a bank builds a loan approval model.

The Decision Tree keeps splitting until each leaf contains only a few customers.

The tree may memorize:

If Credit Score = 721
AND Income = ₹62,345
AND Years Employed = 8
THEN Approve

Instead of learning general approval patterns.

This works perfectly for training data but fails on new applicants.

Visual Representation
Good Fit
Simple Tree
      Credit Score?
         /    \
      Yes      No
   Approve   Reject
Overfitted Tree
Credit Score?
      |
Income?
      |
Age?
      |
Points?
      |
City?
      |
Experience?
      |
...

Too many branches make the model memorize rather than learn.

What is Pruning?

Pruning is the process of reducing the size of a Decision Tree by removing unnecessary branches.

The goal is to:

Reduce overfitting
Improve generalization
Make the model simpler and easier to interpret

2. Post-pruning
Definition

Post-pruning allows the tree to grow completely first.

Then unnecessary branches are removed afterward.

Process

Step 1:

Build a large tree.

Credit Score
     |
Income
     |
Experience
     |
City
     |
Age

Step 2:

Remove branches that do not improve performance.

Credit Score
     |
Income
     |
Approve / Reject
Scikit-Learn Cost Complexity Pruning
DecisionTreeClassifier(
    ccp_alpha=0.01
)

Where:

Small alpha → Larger tree
Large alpha → Smaller tree
Advantages
Usually produces better trees
Less risk of removing useful splits
Better generalization
Disadvantages
More computationally expensive
Requires building a full tree first

Q5. What is Feature Importance?
How can it help businesses in decision-making?

What is Feature Importance?

Feature Importance is a measure of how much each feature (input variable) contributes to a machine learning model's predictions.

In a Decision Tree, features that create the most effective splits are considered more important.

Simply put:

Feature Importance tells us which factors have the greatest influence on the model's decisions.

Example: Loan Approval Model

Suppose a bank builds a Decision Tree using:

Income
Credit Score
Loan Amount
Years Employed
Points

Q6. Data Understanding

Load the dataset

Display first 5 rows

Check:

Shape

Data types

Column names

Interpret:

What types of variables are present?
"""

import pandas as pd
df=pd.read_csv("/content/bank.csv")
df.head()

df.shape

df.dtypes

df.columns

"""Q7. Data Cleaning

Check for missing values

Handle missing values (if any)

Check for duplicates

Interpret:

Is the dataset clean? What issues did you find?
"""

df.isnull().sum()

df.duplicated().sum()

"""If df.isnull().sum().sum() returns 0, there are no missing values.
If df.duplicated().sum() returns 0, there are no duplicate records.
The dataset is considered clean if there are no missing values and no duplicates.
Any missing values or du

Q8. Data Preprocessing



Convert categorical variables into numerical



Mention which encoding method you used

Interpret:



Why is encoding necessary for Decision Trees?
"""

# Convert categorical variables into numerical

categorical_cols = df.select_dtypes(include='object').columns

# One-Hot Encoding
df_encoded = pd.get_dummies(df, columns=categorical_cols, drop_first=True)

df_encoded.head()

"""Interpretation:

Encoding is necessary because Decision Tree algorithms cannot directly process categorical (text) data such as "job", "marital", or "education". Converting these categories into numerical values allows the model to split the data based on feature values and build the decision tree correctly. One-Hot Encoding is preferred because it avoids creating artificial ordinal relationships between categories.

Q9. Feature Selection & Splitting

Separate:

Features (X)

Target (y)

Perform train-test split (80-20)

Interpret:

Why is train-test split important?
"""

# Separate Features (X) and Target (y)

X = df_encoded.drop('deposit_yes', axis=1)
y = df_encoded['deposit_yes']

# Train-Test Split (80% Training, 20% Testing)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

"""Interpretation:

The train-test split is important because it allows us to evaluate the model on unseen data. The model learns patterns from the training set (80%) and its performance is tested on the testing set (20%). This helps measure how well the model generalizes to new data and reduces the risk of overfitting.

Q10. Model Building

Train a Decision Tree Classifier

Use:

criterion='gini'

max_depth=5

Interpret:

What does max_depth control?
"""

# Train a Decision Tree Classifier

from sklearn.tree import DecisionTreeClassifier

dt_model = DecisionTreeClassifier(
    criterion='gini',
    max_depth=5,
    random_state=42
)

dt_model.fit(X_train, y_train)

print("Decision Tree model trained successfully!")

"""Interpretation:

max_depth controls the maximum number of levels (depth) the Decision Tree can grow.

A smaller max_depth creates a simpler tree, reducing the risk of overfitting.
A larger max_depth creates a more complex tree that can capture more patterns but may overfit the training data.
Setting max_depth=5 limits the tree to 5 levels, helping balance model complexity and generalization performance.

Q11. Model Evaluation

Perform:

Accuracy score

Confusion Matrix

Classification Report

Interpret (MUST):

Is the model performing well?

Explain Precision & Recall

Any class imbalance issue?
"""

# Model Evaluation

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Predictions
y_pred = dt_model.predict(X_test)

# Accuracy Score
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy Score:", accuracy)

# Confusion Matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

# Classification Report
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

"""Interpretation

Is the model performing well?
The model's performance should be evaluated using the Accuracy Score, Confusion Matrix, and Classification Report. A high accuracy along with good precision, recall, and F1-score for both classes indicates that the model is performing well.

Explain Precision & Recall

Precision measures how many of the instances predicted as positive are actually positive.

Formula:

Precision=
TP+FP
TP
	​


Higher precision means fewer false positives.

Recall measures how many actual positive instances are correctly identified by the model.

Formula:

Recall=
TP+FN
TP
	​


Higher recall means fewer false negatives.

Any class imbalance issue?

Check the support values in the Classification Report and the class distribution:

print(y.value_counts())
If one class has significantly more records than the other, the dataset has a class imbalance issue.
In such cases, accuracy alone can be misleading, and more attention should be given to Precision, Recall, and F1-score.
If both classes have reasonably similar support values and comparable Precision/Recall scores, class imbalance is not a major concern.

Q12. Overfitting Check

Calculate:

Training accuracy

Testing accuracy

Interpret:

Is the model overfitting or underfitting?
"""

# Training Accuracy

train_accuracy = dt_model.score(X_train, y_train)

# Testing Accuracy

test_accuracy = dt_model.score(X_test, y_test)

print("Training Accuracy:", train_accuracy)
print("Testing Accuracy:", test_accuracy)

"""Interpretation

Is the model overfitting or underfitting?

Compare the Training Accuracy and Testing Accuracy:

Overfitting: Training accuracy is much higher than testing accuracy.
Example: Train = 98%, Test = 80%
The model memorizes training data but performs poorly on new data.
Underfitting: Both training and testing accuracy are low.
Example: Train = 65%, Test = 60%
The model is too simple and fails to learn important patterns.
Good Fit: Training and testing accuracies are both high and close to each other.
Example: Train = 88%, Test = 85%
The model generalizes well to unseen data.

Q13. Pruning Experiment

Train another model with:

max_depth=3

min_samples_split=20

Interpret:

Compare performance with previous model

Which one is better and why?
"""

# Train another Decision Tree model with pruning

from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

dt_pruned = DecisionTreeClassifier(
    criterion='gini',
    max_depth=3,
    min_samples_split=20,
    random_state=42
)

dt_pruned.fit(X_train, y_train)

# Predictions
y_pred_pruned = dt_pruned.predict(X_test)

# Accuracy Scores
train_acc_pruned = dt_pruned.score(X_train, y_train)
test_acc_pruned = dt_pruned.score(X_test, y_test)

print("Pruned Model Training Accuracy:", train_acc_pruned)
print("Pruned Model Testing Accuracy:", test_acc_pruned)

"""Interpretation

Compare Performance with Previous Model

Compare the training and testing accuracies of:

Previous Model
max_depth=5
Pruned Model
max_depth=3
min_samples_split=20

Effect of Pruning:

Lower max_depth makes the tree simpler.
Higher min_samples_split prevents splitting nodes with very few samples.
This reduces model complexity and helps prevent overfitting.
Which Model is Better and Why?
If the pruned model has a testing accuracy similar to or higher than the previous model and a smaller gap between training and testing accuracy, then the pruned model is better because it generalizes better to unseen data.
If the previous model has noticeably higher testing accuracy without significant overfitting, then the previous model is better.

Q14. Feature Importance

Extract top 5 important features

Plot feature importance graph

Interpret:

Which features influence prediction the most?
"""

# Feature Importance

import pandas as pd
import matplotlib.pyplot as plt

# Extract feature importance
feature_importance = pd.DataFrame({
    'Feature': X.columns,
    'Importance': dt_model.feature_importances_
})

# Top 5 important features
top5_features = feature_importance.sort_values(
    by='Importance',
    ascending=False
).head(5)

print("Top 5 Important Features:")
print(top5_features)

# Plot Feature Importance Graph
top5_features.plot(
    x='Feature',
    y='Importance',
    kind='bar',
    legend=False
)

plt.title('Top 5 Feature Importances')
plt.ylabel('Importance Score')
plt.xlabel('Features')
plt.tight_layout()
plt.show()

"""Q15. Business Insights

Based on your model:

Answer:

Which type of customers are more likely to say “yes”?

What strategy should a bank us

1. Which type of customers are more likely to say "Yes"?

Based on the Decision Tree model and the typical importance of features in the Bank Marketing dataset, customers are more likely to subscribe to a term deposit if they:

Have a longer call duration with the bank.
Had a successful previous marketing campaign outcome (poutcome_success).
Have a higher account balance.
Are contacted during months that historically show better conversion rates.
Belong to customer segments that have previously shown interest in banking products.
2. What strategy should a bank use?

Recommended Strategies:

Target customers with higher balances
They are generally more likely to invest in deposit products.
Focus on customers who responded positively in previous campaigns
These customers have a higher probability of converting again.
Improve call quality and customer engagement
Longer and more meaningful conversations tend to increase subscription rates.
Optimize campaign timing
Conduct campaigns during months with historically higher conversion rates.
Use predictive analytics before calling customers
Prioritize customers identified by the model as having a high likelihood of subscribing.
Business Conclusion

The model suggests that customer engagement level, previous campaign success, account balance, and campaign timing are key factors influencing deposit subscriptions. The bank should focus its marketing efforts on high-potential customers and use data-driven targeting to improve conversion rates while reducing marketing costs.
"""