# -*- coding: utf-8 -*-
"""Exploratory Data Analysis (EDA Basics)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yr25AURFM9YI0ACa3qAFojy8XcGgA0yv
"""

# Step 1: Import pandas
import pandas as pd

# Step 2: Upload the CSV file in Google Colab
from google.colab import files
uploaded = files.upload()

# Step 3: Load the dataset
df = pd.read_csv('House Price India.csv')

# Step 4: Display first 5 rows
df.head()

# Basic Information About Dataset
df.info()

# Statistical Summary of Numerical Columns
df.describe()

# Check Missing Values
df.isnull().sum()

# Handle Missing Values

# For numerical columns → fill with median
numerical_cols = df.select_dtypes(include=['int64', 'float64']).columns

for col in numerical_cols:
    df[col].fillna(df[col].median(), inplace=True)

# For categorical columns → fill with mode
categorical_cols = df.select_dtypes(include=['object']).columns

for col in categorical_cols:
    df[col].fillna(df[col].mode()[0], inplace=True)

# Verify again
df.isnull().sum()

"""Q1. What is the average, median, and standard deviation of house prices?"""

# Average, Median, and Standard Deviation of House Prices

average_price = df['Price'].mean()
median_price = df['Price'].median()
std_price = df['Price'].std()

print("Average House Price :", average_price)
print("Median House Price  :", median_price)
print("Standard Deviation  :", std_price)

"""Interpretation
Average Price shows the overall mean house price in the dataset.
Median Price represents the middle value and is less affected by extreme prices/outliers.
Standard Deviation shows how much house prices vary from the average:
Higher value = prices are widely spread
Lower value = prices are more consistent

Q2. Which number of bedrooms is most common?
"""

# Most Common Number of Bedrooms

most_common_bedrooms = df['number of bedrooms'].mode()[0]

print("Most Common Number of Bedrooms :", most_common_bedrooms)

"""Interpretation
The mode() function finds the most frequently occurring number of bedrooms.
This helps identify the most preferred house configuration among buyers.
If a particular bedroom count appears most frequently, it may indicate higher market demand for that house type.

Q3. Check if the price data is skewed.
"""

# Check Skewness of Price Data

skewness = df['Price'].skew()

print("Skewness of House Prices :", skewness)

# Visualize Distribution of House Prices

import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))
plt.hist(df['Price'], bins=30)
plt.title('Distribution of House Prices')
plt.xlabel('House Price')
plt.ylabel('Frequency')
plt.show()

"""Interpretation
Skewness = 0 → Perfectly symmetric distribution
Skewness > 0 → Positively skewed (right-skewed)
Skewness < 0 → Negatively skewed (left-skewed)

Q4. What is the average price for each number of bedrooms?
"""

# Average Price for Each Number of Bedrooms

avg_price_bedrooms = df.groupby('number of bedrooms')['Price'].mean()

print(avg_price_bedrooms)

"""Interpretation
groupby() is used to group houses based on bedroom count.
mean() calculates the average price for each group.
The chart helps compare how house prices change as the number of bedrooms increases.
Usually, houses with more bedrooms tend to have higher average prices.

Q5.  What is the relationship between living area and price? (Use : Area without Basement).
"""

# Relationship Between Living Area and Price

# Correlation between Area without Basement and Price

correlation = df['Area without Basement'].corr(df['Price'])

print("Correlation between Living Area and Price :", correlation)

"""Interpretation
Correlation value tells the strength of relationship:
Close to +1 → Strong positive relationship
Close to 0 → No relationship
Close to -1 → Strong negative relationship
In the scatter plot:
If points move upward from left to right, it indicates a positive relationship.
This means houses with larger living areas generally have higher prices.
Real estate datasets usually show a strong positive relationship between living area and house price.

Q6. Identify any anomalies where houses have high prices but low areas.
"""

# Identify Anomalies:
# Houses with High Prices but Low Areas

# Define thresholds
high_price = df['Price'].quantile(0.90)   # Top 10% prices
low_area = df['Area without Basement'].quantile(0.10)  # Bottom 10% areas

# Filter anomalies
anomalies = df[
    (df['Price'] > high_price) &
    (df['Area without Basement'] < low_area)
]

# Display anomalies
anomalies

"""Interpretation
Anomalies are houses that:
Have very high prices
But comparatively small living areas
These houses may be expensive because of:
Prime location
Luxury interiors
Special amenities
Brand/new construction
Market demand
Such unusual data points are important in real estate analysis because they can affect averages, correlations, and prediction models.

Q7. Compare average price based on number of floors and houses with or without waterfront.
"""

# Compare Average Price Based on:
# 1. Number of Floors
# 2. Waterfront Availability

# Average price by number of floors
avg_price_floors = df.groupby('number of floors')['Price'].mean()

print("Average Price by Number of Floors")
print(avg_price_floors)

# Average price by waterfront

avg_price_waterfront = df.groupby('waterfront present')['Price'].mean()

print("Average Price by Waterfront")
print(avg_price_waterfront)

"""Interpretation
Number of Floors
Houses with more floors generally tend to have higher prices.
Multi-floor houses often provide larger living space and better amenities.
Waterfront
Houses with waterfront views usually have significantly higher prices.
Waterfront properties are considered premium due to:
Better scenery
Higher demand
Luxury value
Comparing these averages helps identify which features influence house prices the most.

Q8. Identify the minimum and maximum house price. What does this indicate?
"""

# Minimum and Maximum House Price

min_price = df['Price'].min()
max_price = df['Price'].max()

print("Minimum House Price :", min_price)
print("Maximum House Price :", max_price)

"""Interpretation
Minimum Price represents the least expensive house in the dataset.
Maximum Price represents the most expensive/luxury house.

Q9. Which location (zipcode/area) has the highest average price?
"""

# Average Price by Zipcode / Area

avg_price_location = df.groupby('zipcode')['Price'].mean()

# Find location with highest average price
highest_price_location = avg_price_location.idxmax()
highest_avg_price = avg_price_location.max()

print("Location with Highest Average Price :", highest_price_location)
print("Highest Average Price :", highest_avg_price)

"""Interpretation
groupby('zipcode') groups houses based on location.
mean() calculates the average house price for each location.
idxmax() identifies the zipcode with the highest average price.

Q10. Write at least 5 insights from your analysis.

Insights from House Price Analysis
House prices are positively skewed
Most houses are moderately priced, while a few luxury houses have extremely high prices.
This creates a right-skewed distribution in the price data.
Larger living areas generally have higher prices
There is a positive relationship between Area without Basement and Price.
Houses with larger living space tend to be more expensive.
Bedroom count influences house prices
Houses with more bedrooms usually have higher average prices.
This indicates buyers are willing to pay more for larger family spaces.
Waterfront properties are significantly more expensive
Houses with waterfront views have a much higher average price compared to non-waterfront houses.
Waterfront is a premium feature in the real estate market.
Location plays a major role in house pricing
Some zipcodes have much higher average prices than others.
Prime locations with better infrastructure and amenities attract higher property values.
"""