# -*- coding: utf-8 -*-
"""Exploratory Data Analysis using Visualization

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hcEJZ43puWQWbLhSiAHiDKurZAi5BrVy

Q1. Create a countplot to show the number of passengers by gender.
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv("/content/Titanic.csv")
df.head()

plt.figure(figsize=(6,4))

sns.countplot(x='Sex', data=df)

plt.title("Number of Passengers by Gender")
plt.xlabel("Gender")
plt.ylabel("Number of Passengers")

plt.show()

"""Q2. Create a bar chart to show the number of passengers in each passenger class using different colors."""

plt.figure(figsize=(7,5))

# Create countplot with different colors
sns.countplot(x='Pclass', data=df, palette='Set2')

# Add title and labels
plt.title("Number of Passengers in Each Passenger Class")
plt.xlabel("Passenger Class")
plt.ylabel("Number of Passengers")

# Show plot
plt.show()

"""Q3. Create a histogram to show the distribution of passenger age."""

plt.figure(figsize=(8,5))

# Create histogram
sns.histplot(df['Age'], bins=20, kde=True, color='skyblue')

# Add title and labels
plt.title("Distribution of Passenger Age")
plt.xlabel("Age")
plt.ylabel("Number of Passengers")

# Show plot
plt.show()

"""Interpretation:
Most passengers were between 20 and 40 years old.
There were fewer elderly passengers and very young children.
The age distribution is slightly right-skewed, showing more young adults on the Titanic.

Q4. Create a boxplot to detect outliers in the fare column.
"""

# Create figure
plt.figure(figsize=(8,5))

# Create boxplot
sns.boxplot(x=df['Fare'], color='lightgreen')

# Add title and labels
plt.title("Boxplot of Passenger Fare")
plt.xlabel("Fare")

# Show plot
plt.show()

"""Interpretation:
The boxplot shows several outliers in the Fare column.
Some passengers paid extremely high fares compared to others.
Most passengers paid lower ticket fares, while a few paid very expensive fares, likely for higher-class cabins.

Q5. Create a scatterplot to

 a. show the relationship between age and fare.

 b. analyze the relationship between family size (SibSp + Parch) and fare.
"""

# Create figure
plt.figure(figsize=(8,5))

# Create scatterplot
sns.scatterplot(x='Age', y='Fare', data=df)

# Add title and labels
plt.title("Relationship Between Age and Fare")
plt.xlabel("Age")
plt.ylabel("Fare")

# Show plot
plt.show()

"""Interpretation:
There is no strong linear relationship between Age and Fare.
Some passengers with higher fares belong to different age groups.
A few passengers paid very high fares, creating visible outliers
"""

# Create Family Size column
df['FamilySize'] = df['SibSp'] + df['Parch']

# Create figure
plt.figure(figsize=(8,5))

# Create scatterplot
sns.scatterplot(x='FamilySize', y='Fare', data=df)

# Add title and labels
plt.title("Relationship Between Family Size and Fare")
plt.xlabel("Family Size")
plt.ylabel("Fare")

# Show plot
plt.show()

"""Interpretation:
Passengers with larger family sizes often paid higher fares.
Most passengers traveled alone or with small families.
Some high-fare outliers are visible even for smaller family sizes.

Q6. Create a countplot to show survival count by gender.
"""

# Create figure
plt.figure(figsize=(7,5))

# Create countplot
sns.countplot(x='Sex', hue='Survived', data=df, palette='Set1')

# Add title and labels
plt.title("Survival Count by Gender")
plt.xlabel("Gender")
plt.ylabel("Number of Passengers")

# Rename legend labels
plt.legend(title='Survived', labels=['No', 'Yes'])

# Show plot
plt.show()

"""Interpretation:
Female passengers had a higher survival rate compared to male passengers.
Most male passengers did not survive.
The chart suggests that women were given higher priority during rescue operations.

Q7. Create a bar chart to show survival by passenger class.
"""

# Create figure
plt.figure(figsize=(7,5))

# Create countplot
sns.countplot(x='Pclass', hue='Survived', data=df, palette='Set2')

# Add title and labels
plt.title("Survival by Passenger Class")
plt.xlabel("Passenger Class")
plt.ylabel("Number of Passengers")

# Rename legend labels
plt.legend(title='Survived', labels=['No', 'Yes'])

# Show plot
plt.show()

"""Interpretation:
First-class passengers had a higher survival rate compared to lower classes.
Third-class passengers had the highest number of deaths.
Passenger class played an important role in survival chances on the Titanic.

Q8. Create a heatmap to show correlation between numerical variables.
"""

# Select numerical columns and calculate correlation
corr_matrix = df.corr(numeric_only=True)

# Create figure
plt.figure(figsize=(12,8))

# Create heatmap
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt='.2f')

# Add title
plt.title("Correlation Heatmap of Numerical Variables")

# Show plot
plt.show()

"""Interpretation:
Variables closer to +1 have a strong positive correlation.
Variables closer to -1 have a strong negative correlation.
Survival is positively related to Fare and negatively related to Pclass.
Some variables show weak or almost no correlation with each other.

Q9. Identify which passenger class paid the highest fare on average.
"""

# Calculate average fare by passenger class
avg_fare = df.groupby('Pclass')['Fare'].mean()

# Display average fares
print(avg_fare)

# Create bar chart
plt.figure(figsize=(7,5))

sns.barplot(x=avg_fare.index, y=avg_fare.values, palette='Set3')

# Add title and labels
plt.title("Average Fare by Passenger Class")
plt.xlabel("Passenger Class")
plt.ylabel("Average Fare")

# Show plot
plt.show()

"""Interpretation:
Passenger Class 1 paid the highest average fare.
Passenger Class 3 paid the lowest average fare.
Higher passenger classes were associated with more expensive ticket prices on the Titanic.

Q10. Write at least 5 insights from the dataset based on your visualizations.

Male passengers were more than female passengers
The dataset shows that the Titanic had a significantly higher number of male passengers compared to female passengers.
Female passengers had a higher survival rate
Survival analysis indicates that women were more likely to survive than men, suggesting priority was given to females during rescue operations.
Passenger Class 1 had the highest survival rate
First-class passengers survived more often than passengers in Classes 2 and 3, showing that socio-economic status influenced survival chances.
Most passengers belonged to Passenger Class 3
The majority of passengers traveled in third class, making it the most crowded passenger category on the Titanic.
Passenger Class 1 paid the highest fares
Average fare analysis showed that first-class passengers paid significantly higher ticket prices than lower classes.
"""