# -*- coding: utf-8 -*-
"""Libraries: NumPy & Pandas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GwSfkyUYdT1_ur7jZEysFtjI6YJ7kwiI

Q1. Load the given retail sales dataset into a Pandas DataFrame and display the first 5 rows along with the dataset information to understand its structure.
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_csv("retail_dataset.csv")
print(df.head())

"""Q2. Inspect the dataset and identify missing values in each column. Display the total number of missing
values present in the dataset.

"""

df.isnull().sum()
df.isnull().sum().sum()

"""Q3. Replace missing values in the Quantity and Price columns with their respective mean values using
Pandas.
"""

df['Quantity'].mean()
df['Price'].mean()

df['Quantity'] = df['Quantity'].fillna(df['Quantity'].mean())
df['Price'] = df['Price'].fillna(df['Price'].mean())

"""Q4. Remove all rows where the Product Category or Region column contains missing values."""

df = df.dropna(subset=['Product Category', 'Region'])

"""Q5. Create a new column called Revenue using NumPy, where:

Revenue = Quantity × Price

Display the updated dataset with the new column.
"""

import numpy as np
df['Revenue'] = np.multiply(df['Quantity'], df['Price'])
print(df.head())

"""Q6. Using NumPy, calculate the total revenue generated from all transactions in the dataset."""

import numpy as np

total_revenue = np.sum(df['Revenue'])
print("Total Revenue:", total_revenue)

"""Q7. Group the dataset by Product Category and calculate the total revenue generated by each category."""

category_revenue = df.groupby('Product Category')['Revenue'].sum()
print(category_revenue)

"""Q8. Based on the revenue calculated for each product category, identify the top 3 categories with the
highest revenue and the bottom 3 categories with the lowest revenue.
"""

category_revenue = df.groupby('Product Category')['Revenue'].sum()
top_3 = category_revenue.sort_values(ascending=False).head(3)
print("Top 3 Categories:\n", top_3)
bottom_3 = category_revenue.sort_values(ascending=True).head(3)
print("\nBottom 3 Categories:\n", bottom_3)

"""Q9. Group the dataset by Region and calculate the total revenue generated in each region. Identify the
region with the highest revenue and the region with the lowest revenue.
"""

region_revenue = df.groupby('Region')['Revenue'].sum()
print(region_revenue)
highest_region = region_revenue.idxmax()
lowest_region = region_revenue.idxmin()

print("Highest Revenue Region:", highest_region)
print("Lowest Revenue Region:", lowest_region)

"""Q10. Extract the month from the Date column using Pandas and group the dataset by month to calculate the
total monthly revenue. Also, calculate the mean, median, and standard deviation of the Revenue column
using NumPy.
"""

df['Date'] = pd.to_datetime(df['Date'], dayfirst=True)
df['Month'] = df['Date'].dt.month
df['Month'] = df['Date'].dt.month_name()
monthly_revenue = df.groupby('Month')['Revenue'].sum()
print(monthly_revenue)
import numpy as np

mean_revenue = np.mean(df['Revenue'])
median_revenue = np.median(df['Revenue'])
std_revenue = np.std(df['Revenue'])

print("Mean Revenue:", mean_revenue)
print("Median Revenue:", median_revenue)
print("Standard Deviation:", std_revenue)