# -*- coding: utf-8 -*-
"""Logistic Regression (Loan Approval Prediction)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e62MzHmrhsGeRh2qHw2yiSK0lE5FLhH1
"""

Q1. Data Loading & Understanding

a) Load the dataset into Python.
b) Display the first 5 rows.
c) Check the shape of the dataset.
d) Display the data types of each column.

import pandas as pd

df = pd.read_csv("/content/loan_approval - loan_approval.csv")
df.head(5)

df.shape
df.dtypes

"""Q2. Data Cleaning

a) Check for missing values in the dataset.
b) Handle missing values appropriately.
c) Identify categorical columns present in the dataset.
"""

# Check missing values
df.isnull().sum()

# Total missing values in dataset
df.isnull().sum().sum()

# Identify categorical columns
categorical_cols = df.select_dtypes(include=['object']).columns
categorical_cols

"""Q3. Exploratory Data Analysis (EDA)

a) Plot the distribution of the target variable.
b) Analyze the relationship between one numerical feature and the target variable.
c) Analyze the relationship between Years of Employment and the target variable.
"""

import matplotlib.pyplot as plt
import seaborn as sns

sns.countplot(x='loan_approved', data=df)

plt.title('Distribution of Loan Approval Status')
plt.xlabel('Loan Approved')
plt.ylabel('Count')
plt.show()

plt.figure(figsize=(8,5))

sns.boxplot(x='loan_approved',
            y='credit_score',
            data=df)

plt.title('Credit Score vs Loan Approval')
plt.xlabel('Loan Approved')
plt.ylabel('Credit Score')
plt.show()

plt.figure(figsize=(8,5))

sns.boxplot(x='loan_approved',
            y='years_employed',
            data=df)

plt.title('Years of Employment vs Loan Approval')
plt.xlabel('Loan Approved')
plt.ylabel('Years Employed')
plt.show()

"""Q4. Outlier Detection and Treatment

a) Detect outliers in numerical columns using the IQR method.
b) Treat outliers using capping techniques
"""

numerical_cols = ['income',
                  'credit_score',
                  'loan_amount',
                  'years_employed',
                  'points']

for col in numerical_cols:

    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)

    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = df[(df[col] < lower_bound) |
                  (df[col] > upper_bound)]

    print(f"{col}: {len(outliers)} outliers")

import matplotlib.pyplot as plt
import seaborn as sns

for col in numerical_cols:
    plt.figure(figsize=(6,3))
    sns.boxplot(x=df[col])
    plt.title(f'Boxplot of {col}')
    plt.show()

df_cap = df.copy()

for col in numerical_cols:

    Q1 = df_cap[col].quantile(0.25)
    Q3 = df_cap[col].quantile(0.75)

    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    df_cap[col] = df_cap[col].clip(lower=lower,
                                   upper=upper)

for col in numerical_cols:

    Q1 = df_cap[col].quantile(0.25)
    Q3 = df_cap[col].quantile(0.75)

    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = df_cap[
        (df_cap[col] < lower) |
        (df_cap[col] > upper)
    ]

    print(f"{col}: {len(outliers)} outliers")

"""Q5. Convert target variables into numerical format suitable for model building and drop unnecessary
columns.
"""

df['loan_approved'].head()

df['loan_approved'] = df['loan_approved'].astype(int)
df['loan_approved'].head()

df['loan_approved'].unique()

df_model = df.drop(['name', 'city'], axis=1)

"""Q6. Feature Selection and Data Splitting



a) Separate independent variables (X) and dependent variable (y).

b) Split the dataset into training and testing sets.
"""

X = df_model.drop('loan_approved', axis=1)

y = df_model['loan_approved']
X.head()

print("X Shape:", X.shape)
print("y Shape:", y.shape)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

X_train: (1600, 5)
X_test : (400, 5)

y_train: (1600,)
y_test : (400,)

"""Q7. Apply feature scaling to the dataset using StandardScaler."""

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)

X_test_scaled = scaler.transform(X_test)

X_train_scaled[:5]

X_train_scaled.mean(axis=0)

X_train_scaled.std(axis=0)

"""Q8. Logistic Regression Model Building

a) Train a Logistic Regression model.
b) Predict the output for test data.
"""

from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression()

log_reg.fit(X_train_scaled, y_train)

print("Model Training Completed Successfully")

print("Intercept:", log_reg.intercept_)
print("Coefficients:", log_reg.coef_)

y_pred = log_reg.predict(X_test_scaled)

print(y_pred[:10])

"""Q9. Model Evaluation – Confusion Matrix

a) Generate the confusion matrix.
b) Interpret the results.
"""

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

print(cm)

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(6,4))

sns.heatmap(cm,
            annot=True,
            fmt='d',
            cmap='Blues',
            xticklabels=['Rejected', 'Approved'],
            yticklabels=['Rejected', 'Approved'])

plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix')
plt.show()

"""Q10. Model Evaluation – ROC Curve & AUC

a) Plot the ROC curve.
b) Calculate the AUC score.
"""

from sklearn.metrics import roc_curve, roc_auc_score
import matplotlib.pyplot as plt

y_prob = log_reg.predict_proba(X_test_scaled)[:, 1]

fpr, tpr, thresholds = roc_curve(y_test, y_prob)

plt.figure(figsize=(8,6))

plt.plot(fpr, tpr,
         label='Logistic Regression')

plt.plot([0,1], [0,1],
         linestyle='--',
         label='Random Classifier')

plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve')

plt.legend()
plt.show()

auc_score = roc_auc_score(y_test, y_prob)

print("AUC Score:", auc_score)