# -*- coding: utf-8 -*-
"""ML Basics & Linear Regression

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14RmlQXDaZ1VrEpwa3C2Ec_RtDpBTI1mE

Q1. What is Machine Learning? Explain the main types of Machine Learning with examples.

Machine Learning (ML) is a branch of Artificial Intelligence (AI) that enables computers to learn from data and make predictions or decisions without being explicitly programmed. Instead of following fixed rules, machine learning algorithms identify patterns in data and improve their performance over time.

Main Types of Machine Learning
1. Supervised Learning

In supervised learning, the model is trained using labeled data, where both input and output values are known. The goal is to learn the relationship between inputs and outputs and make predictions on new data.

Examples:

Predicting house prices based on size, location, and number of rooms.
Email spam detection.
Student exam score prediction.

Algorithms:

Linear Regression
Logistic Regression
Decision Trees
Random Forest
2. Unsupervised Learning

In unsupervised learning, the model is trained using unlabeled data. The algorithm identifies hidden patterns, relationships, or groups within the data.

Examples:

Customer segmentation in marketing.
Grouping similar products.
Fraud detection through anomaly identification.

Algorithms:

K-Means Clustering
Hierarchical Clustering
Principal Component Analysis (PCA)
3. Reinforcement Learning

In reinforcement learning, an agent learns by interacting with an environment and receiving rewards or penalties for its actions. The goal is to maximize the total reward over time.

Examples:

Self-driving cars.
Game-playing AI such as chess or Go.
Robot navigation systems.

Algorithms:

Q-Learning
Deep Q Networks (DQN)

Q2. What is Supervised Learning? Explain the difference between Regression and Classification.

Supervised Learning is a type of Machine Learning in which the model is trained using labeled data. In labeled data, both the input variables (features) and the correct output (target) are known. The model learns the relationship between inputs and outputs and uses this knowledge to make predictions on new data.

Examples of Supervised Learning:

Predicting house prices.
Predicting employee attrition.
Email spam detection.
Disease diagnosis.
Difference Between Regression and Classification
Feature	Regression	Classification
Purpose	Predicts continuous numerical values	Predicts categorical values or classes
Output Type	Numeric value	Category or label
Example	Predicting house price, salary, sales	Predicting spam/not spam, pass/fail
Target Variable	Continuous	Discrete
Common Algorithms	Linear Regression, Random Forest Regressor	Logistic Regression, Decision Tree, Random Forest Classifier
Regression

Regression is used when the target variable is a continuous numerical value.

Examples:

Predicting house prices.
Predicting monthly sales.
Predicting employee salaries.

Output Example:

House Price = ₹45,00,000
Sales = 12,500 units
Classification

Classification is used when the target variable belongs to a specific category or class.

Examples:

Spam or Not Spam email.
Customer will leave or stay.
Pass or Fail prediction.

Output Example:

Spam
Not Spam
Yes
No

Q3. What is Linear Regression? Write the Linear Regression equation and explain intercept and coefficient.

Linear Regression is a supervised machine learning algorithm used to predict a continuous numerical value based on one or more independent variables. It establishes a linear relationship between the input variables and the target variable by fitting the best possible straight line through the data.

Examples:

Predicting house prices.
Predicting employee salaries.
Predicting sales revenue.
Predicting stock demand.
Linear Regression Equation

For a simple linear regression with one independent variable:

Y=b
0
	​

+b
1
	​

X

Where:

Y = Dependent variable (target/output)
X = Independent variable (input/feature)
b₀ = Intercept
b₁ = Coefficient (slope)
Ŷ = Predicted value of Y

For multiple linear regression:

Y=b
0
	​

+b
1
	​

X
1
	​

+b
2
	​

X
2
	​

+⋯+b
n
	​

X
n
	​


Intercept (b₀)

The intercept is the value of the target variable when all independent variables are equal to zero. It represents the starting point of the regression line.

Example:

If the equation is:

Y = 10 + 5X

The intercept is 10, meaning when X = 0, the predicted value of Y is 10.

Coefficient (b₁)

The coefficient represents the amount by which the target variable changes when the independent variable increases by one unit, keeping all other variables constant.

Example:

If the equation is:

Y = 10 + 5X

The coefficient is 5, meaning for every 1-unit increase in X, Y increases by 5 units.

Example

Suppose a house price prediction model has the equation:

Price = 50 + 20 × Rooms

Intercept = 50
Coefficient of Rooms = 20

Interpretation:

A house with 0 rooms would have a predicted price of 50 (theoretical value).
For every additional room, the house price increases by 20 units.

Q4. Explain the following evaluation metrics used in Linear Regression:

SSE

MSE

RMSE

R² Score

Adjusted R

Evaluation metrics are used to measure how well a Linear Regression model predicts the target variable. They help determine the accuracy and performance of the model.

1. SSE (Sum of Squared Errors)

SSE is the sum of the squared differences between the actual values and the predicted values.

SSE=∑
i=1
n
	​

(Y
i
	​

−
Y
^
i
	​

)
2

Where:

Y
i
	​

 = Actual value
Y
^
i
	​

 = Predicted value
n = Number of observations

Interpretation:

Lower SSE indicates a better model.
SSE = 0 means perfect predictions.
2. MSE (Mean Squared Error)

MSE is the average of the squared errors.

MSE=
n
1
	​

∑
i=1
n
	​

(Y
i
	​

−
Y
^
i
	​

)
2

Interpretation:

Measures the average prediction error.
Larger errors are penalized more because errors are squared.
Lower MSE indicates better model performance.
3. RMSE (Root Mean Squared Error)

RMSE is the square root of MSE.

RMSE=
MSE
	​


Interpretation:

Represents the average prediction error in the same unit as the target variable.
Easier to interpret than MSE.
Lower RMSE indicates better predictions.

Example:
If RMSE = 3, the model's predictions are off by about 3 units on average.

4. R² Score (Coefficient of Determination)

R² measures how much of the variation in the target variable is explained by the model.

R
2
=1−
SST
SSE
	​


Where:

SSE = Sum of Squared Errors
SST = Total Sum of Squares

Interpretation:

R² = 1 → Perfect fit
R² = 0 → Model explains none of the variability
Higher R² is generally better

Example:

R² = 0.85 means the model explains 85% of the variation in the target variable.
5. Adjusted R²

Adjusted R² is a modified version of R² that accounts for the number of independent variables in the model.

Adjusted R
2
=1−(
n−k−1
(1−R
2
)(n−1)
	​

)

Where:

n = Number of observations
k = Number of independent variables

Interpretation:

Penalizes unnecessary features.
Helps determine whether adding a new variable actually improves the model.
Preferred over R² when comparing models with different numbers of features.

Q5. Explain the Machine Learning workflow steps from data collection to model evaluation.

1. Data Collection

The first step is to gather relevant data from various sources such as databases, spreadsheets, APIs, websites, sensors, or business applications.

Examples:

Customer data from a CRM system.
Sales data from Excel files.
Employee data from an HR database.

Goal: Obtain sufficient and relevant data for analysis.

2. Data Preprocessing

Raw data often contains missing values, duplicates, incorrect entries, or inconsistencies. Data preprocessing prepares the data for modeling.

Tasks:

Handle missing values.
Remove duplicates.
Correct data errors.
Convert categorical data into numerical form.
Scale or normalize data if required.

Goal: Create a clean and usable dataset.

3. Exploratory Data Analysis (EDA)

EDA helps understand the dataset and discover patterns, trends, and relationships between variables.

Techniques:

Histograms
Boxplots
Scatterplots
Correlation analysis
Summary statistics

Goal: Gain insights and identify important features.

4. Feature Selection and Feature Engineering

Feature Selection involves choosing the most relevant variables for prediction.

Feature Engineering involves creating new features from existing data to improve model performance.

Examples:

Creating "Family Size" from SibSp and Parch in the Titanic dataset.
Extracting month and year from a date column.

Goal: Improve model accuracy and efficiency.

5. Train-Test Split

The dataset is divided into two parts:

Training Set: Used to train the model.
Testing Set: Used to evaluate the model.

A common split is:

80% Training Data
20% Testing Data

Goal: Test the model on unseen data.

6. Model Selection

Choose an appropriate machine learning algorithm based on the problem type.

Examples:

For Regression:

Linear Regression
Random Forest Regressor

For Classification:

Logistic Regression
Decision Tree
Random Forest Classifier

Goal: Select the best algorithm for the task.

7. Model Training

The selected algorithm learns patterns from the training data.

model.fit(X_train, Y_train)

Goal: Build a model that can make predictions.

8. Model Prediction

After training, the model predicts outcomes using the test data.

Y_pred = model.predict(X_test)

Goal: Generate predictions for unseen data.

9. Model Evaluation

Evaluate the model's performance using suitable metrics.

For Regression:

MSE
RMSE
MAE
R² Score

For Classification:

Accuracy
Precision
Recall
F1 Score
Confusion Matrix

Q6. Load the Boston Housing dataset and perform basic data exploration using:

head()

info()

describe()
"""

import pandas as pd
df=pd.read_csv("/content/BostonHousing.csv")
df.head()

df.info()
df.describe()

"""Q7. Perform Exploratory Data Analysis:

Create pairplot

Create correlation heatmap

Identify which features are highly correlated with house price (medv)
"""

import seaborn as sns
import matplotlib.pyplot as plt

# Calculate correlation matrix
corr_matrix = df.corr()

# Create heatmap
plt.figure(figsize=(12,8))
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt='.2f')

plt.title("Correlation Heatmap")
plt.show()

# Correlation of all features with MEDV
corr_with_medv = df.corr()['medv'].sort_values(ascending=False)

print(corr_with_medv)

"""Q8. Select independent variables (features) and dependent variable (target).
 Target variable: medv (house price)
"""

# Independent Variables (Features)
X = df.drop('medv', axis=1)

# Dependent Variable (Target)
Y = df['medv']

# Display shapes
print("Features Shape:", X.shape)
print("Target Shape:", Y.shape)

"""Q9. Split the dataset into training and testing sets (80% training, 20% testing)."""

from sklearn.model_selection import train_test_split

# Split the dataset
X_train, X_test, Y_train, Y_test = train_test_split(
    X, Y,
    test_size=0.20,
    random_state=42
)

# Display shapes
print("X_train Shape:", X_train.shape)
print("X_test Shape:", X_test.shape)
print("Y_train Shape:", Y_train.shape)
print("Y_test Shape:", Y_test.shape)

"""Q10. Train a Linear Regression model and perform the following:

Make predictions

Calculate MAE

Calculate MSE

Calculate RMSE

Calculate R² Score

Calculate Adjusted R²

Write the Linear Regression equation

Interpret the model coefficients
"""

from sklearn.linear_model import LinearRegression

# Create model
model = LinearRegression()

# Train model
model.fit(X_train, Y_train)

# Predict on test data
Y_pred = model.predict(X_test)

print(Y_pred[:10])

from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
import numpy as np

# Evaluation Metrics
mae = mean_absolute_error(Y_test, Y_pred)
mse = mean_squared_error(Y_test, Y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(Y_test, Y_pred)

print("MAE :", mae)
print("MSE :", mse)
print("RMSE :", rmse)
print("R² Score :", r2)

n = X_test.shape[0]      # Number of observations
p = X_test.shape[1]      # Number of features

adjusted_r2 = 1 - ((1-r2)*(n-1)/(n-p-1))

print("Adjusted R² :", adjusted_r2)

print("Intercept:", model.intercept_)
print("Coefficients:", model.coef_)