# -*- coding: utf-8 -*-
"""Pandas Dataframe

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p7kp0H2_aJ3gEwUHzZfxhSj3RrHOGhDg

Q1. Creating a DataFrame

Create a Pandas DataFrame using a Python dictionary with the following columns:

Product

Region

Sales

Quantity


Add at least 5 rows of sample data and display the DataFrame.
"""

import pandas as pd

# Create dictionary
data = {
    'Product': ['Laptop', 'Mobile', 'Tablet', 'Headphones', 'Monitor'],
    'Region': ['North', 'South', 'East', 'West', 'North'],
    'Sales': [80000, 50000, 30000, 10000, 20000],
    'Quantity': [5, 10, 7, 15, 6]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display DataFrame
print(df)

"""Q2. Data Inspection

Perform the following inspection tasks:

Display the first 5 rows of the dataset.

Display the last 5 rows.

Show the structure of the dataset using info().

Display the shape of the dataset.
"""

df.head()
df.tail()
df.info()
df.shape

"""Q3. Column Selection

Select and display only the following columns:

Product

Region

Sales
"""

df[['Product', 'Region', 'Sales']]

"""Q4. Indexing using .loc, perform the following:

Display the row with index 10.

Display the Sales value of the row with index 20
"""

df.loc[10]
df.loc[20, 'Sales']

"""Q5. Indexing using .iloc

Using .iloc, display:

The first 6 rows and first 4 columns.

The Sales value from the 3rd row.
"""

df.iloc[0:6, 0:4]

df.iloc[2]['Sales']

"""Q6. Row Slicing

Display:

The first 10 rows of the dataset.

Rows 15 to 25
"""

df.iloc[0:10]

df.iloc[15:26]

"""Q7. Filtering Data

Filter the dataset to display:

Rows where Region = "East".

Rows where Sales > 1500.
"""

df[df['Region'] == 'East']

df[df['Sales'] > 1500]

"""Q8. Multiple Condition Filtering

Display rows where:

Region is West

Sales is greater than 1200
"""

df[(df['Region'] == 'West') & (df['Sales'] > 1200)]

"""Q9. Descriptive Statistics

Generate summary statistics using:

describe()

From the result identify:

Mean sales value

Maximum quantity sold

Minimum sales value
"""

df.describe()

mean_sales = df['Sales'].mean()
max_quantity = df['Quantity'].max()
min_sales = df['Sales'].min()

print("Mean Sales:", mean_sales)
print("Max Quantity:", max_quantity)
print("Min Sales:", min_sales)

"""Q10. Aggregation Analysis

Using the Sales column, calculate:

Total sales

Average sales

Maximum sales

Minimum sales
"""

total_sales = df['Sales'].sum()
avg_sales = df['Sales'].mean()
max_sales = df['Sales'].max()
min_sales = df['Sales'].min()

print("Total Sales:", total_sales)
print("Average Sales:", avg_sales)
print("Maximum Sales:", max_sales)
print("Minimum Sales:", min_sales)